# Laboratorio | Pandas

En este laboratorio trabajaremos con datos de clientes de una compañía de seguros. Los datos se encuentran en el archivo CSV disponible en el siguiente enlace: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

Los datos incluyen información como el identificador del cliente, el estado donde vive, el género, la educación, los ingresos y otras variables que se pueden utilizar para realizar distintos análisis.

A lo largo del laboratorio utilizaremos la biblioteca pandas de Python para manipular y analizar los datos. Pandas es una biblioteca potente que ofrece diversas herramientas para trabajar con datos, entre ellas la posibilidad de cargar y manipular información procedente de distintas fuentes, incluidos archivos CSV.

### Descripción de los datos

- **Customer**: identificador del cliente.

- **ST**: estado en el que viven los clientes.

- **Gender**: género del cliente.

- **Education**: nivel educativo del cliente.

- **Customer Lifetime Value**: el valor de vida del cliente (*Customer Lifetime Value*, CLV) es el ingreso total que la empresa espera obtener de un cliente durante toda su relación con él. En otras palabras, es el valor previsto o calculado de un cliente durante todo el tiempo que mantenga una póliza con la compañía de seguros. Es una estimación del beneficio neto que la aseguradora espera generar a lo largo de esa relación. El valor de vida del cliente tiene en cuenta factores como la duración de la póliza, los pagos de las primas, el historial de reclamaciones, la probabilidad de renovación y la posibilidad de que el cliente contrate servicios o productos adicionales. Ayuda a las aseguradoras a evaluar la rentabilidad a largo plazo y el valor de conservar a un cliente.

- **Income**: ingresos del cliente.

- **Monthly Premium Auto**: cantidad que el cliente paga mensualmente por la prima de su seguro de automóvil. Representa el coste recurrente que la persona asegurada debe pagar para mantener la póliza y contar con cobertura frente a posibles daños, accidentes u otros sucesos relacionados con su vehículo que estén cubiertos por el seguro.

- **Number of Open Complaints**: número de reclamaciones que ha abierto el cliente.

- **Policy Type**: existen tres tipos de pólizas de seguro de automóvil: *Corporate Auto*, *Personal Auto* y *Special Auto*.

- **Vehicle Class**: categoría del vehículo del cliente: coche de dos puertas, coche de cuatro puertas, SUV, SUV de lujo, coche deportivo y coche de lujo.

- **Total Claim Amount**: suma de todas las reclamaciones presentadas por el cliente. Representa el valor monetario total de las reclamaciones aprobadas por incidentes como accidentes, robos, actos vandálicos u otros sucesos cubiertos por la póliza.

Recursos externos: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Reto 1: Comprender los datos

En este reto utilizarás pandas para explorar un conjunto de datos. Tu objetivo es comprenderlo en profundidad mediante el análisis de sus características, dimensiones y propiedades estadísticas.

- Identifica las dimensiones del conjunto de datos determinando cuántas filas y columnas contiene.
- Determina los tipos de datos de cada columna y evalúa si son adecuados para la naturaleza de la variable. También debes sugerir cómo corregir los tipos de datos que sean incorrectos.
- Identifica el número de valores únicos de cada columna y determina cuáles parecen ser categóricas. Describe también los valores únicos de cada columna categórica y el rango de valores de las columnas numéricas, y aporta tus conclusiones.
- Calcula estadísticas descriptivas, como la media, la mediana, la moda, la desviación estándar y los cuartiles, para comprender la tendencia central y la distribución de los datos de las columnas numéricas. Expón también tus conclusiones a partir de estas estadísticas.
- Calcula estadísticas descriptivas para las columnas categóricas y presenta tus conclusiones a partir de ellas.

In [20]:
# Your code here
import pandas as pd 
data = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv')
print(data.shape)
print(data.info())

(4008, 11)
<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   str
 1   ST                         1071 non-null   str
 2   GENDER                     954 non-null    str
 3   Education                  1071 non-null   str
 4   Customer Lifetime Value    1068 non-null   str
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   str
 8   Policy Type                1071 non-null   str
 9   Vehicle Class              1071 non-null   str
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 344.6 KB
None

In [24]:
data.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

#Al revisar los datos se puede ver como en en la columna "Customer Life Time Value" hay que eliminar los porcentajes por lo que en realidad es para la empresa, un beneficio monetario para la empresa, por lo que la propuesta sería convertirlo a un tipo de dato "Float 64".
En cuanto a Number of Open Complaints, debe ser cambiado a "int64" al tratarse del numero de reclamaciones para el seguro, quienes en str pueden tener sentido para un humano pero al sumarlos, python no los interpreta de la misma manera y da error al no poder sumar texto.

In [8]:
unique_values = data.columns
unique_values.unique()

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

In [10]:
data.nunique()

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

#Identificación del número de valores únicos de cada columna

In [26]:
data[['ST', 'GENDER', 'Education', 'Vehicle Class', 'Policy Type', 'Customer', 'Number of Open Complaints']].nunique()

ST                              8
GENDER                          5
Education                       6
Vehicle Class                   6
Policy Type                     3
Customer                     1071
Number of Open Complaints       6
dtype: int64

#determina cuáles parecen ser categóricas

In [27]:
print(data['Vehicle Class'].unique())
print(data['Policy Type'].unique())
print(data['GENDER'].unique())
print(data['Education'].unique())
print(data['ST'].unique())
print(data['Customer'].unique())
print(data['Number of Open Complaints'].unique())

<StringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car',             nan]
Length: 7, dtype: str
<StringArray>
['Personal Auto', 'Corporate Auto', 'Special Auto', nan]
Length: 4, dtype: str
<StringArray>
[nan, 'F', 'M', 'Femal', 'Male', 'female']
Length: 6, dtype: str
<StringArray>
[              'Master',             'Bachelor', 'High School or Below',
              'College',            'Bachelors',               'Doctor',
                    nan]
Length: 7, dtype: str
<StringArray>
['Washington',    'Arizona',     'Nevada', 'California',     'Oregon',
       'Cali',         'AZ',         'WA',          nan]
Length: 9, dtype: str
<StringArray>
['RB50392', 'QZ44356', 'AI49188', 'WW63253', 'GA49547', 'OC83172', 'XZ87318',
 'CF85061', 'DY87989', 'BQ94931',
 ...
 'IK12620', 'GQ66762', 'YT69858', 'XD85577', 'TM65736', 'VJ51327', 'GS98873',
 'CW49887', 'MY31220',       nan]
Length: 1072, dtype: str
<StringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str


#Categorias:
Vehicle Class: Tiene 6 valores unicos y 1 valor ausente.
Policy Type: Tiene 3 valores unicos y 1 valor ausente.
GENDER: Contiene 5 valores unicos y 1 dato ausente. En este punto sería importante revisar que no hayan existido errores, ya que F podría siginficar lo mismo que Feamle o Femal. 
Education: Contiene 6 diferentes niveles educativos y 1 valor ausente. En este habría que revisar si Bachelor y Bachelors sigifican lo mismo y corresponde mas biena un error de digitación. 
ST: Contiene 8 valores diferentes y un valor ausente. En este, los datos de 'Cali', 'AZ', 'WA' podrian siginificar lo mismo que California, Washington y Arizona pero escritos de manera diferente. 
Customer: Hay 1071 valores de identificador distintos en esta columna y 1 valor ausente. 
Number of Open Complaints: Contiene 7 valores unicos. en este punto se tendría que revisar porque en en un numero ttoal de quejas abiertas para un prestador de seguros, el fomrato se enuentra como si fuese una fecha.

In [30]:
print(data['Customer Lifetime Value'].max())
print(data['Customer Lifetime Value'].min())

995170.77%
1006460.83%

In [31]:
print(data['Income'].max())
print(data['Income'].min())

99960.0
0.0

In [32]:
print(data['Monthly Premium Auto'].max())
print(data['Monthly Premium Auto'].min())

35354.0
61.0

In [33]:
print(data['Total Claim Amount'].max())
print(data['Total Claim Amount'].min())

2893.239678
0.382107

# Analisis:
Income: los ingresos van de 0 a 99.960. Es posible que existan clientes con ingresos nulos; no debemos asumir que sea un error sin investigar.



Monthly Premium Auto: los valores van de 61 a 35.354. El máximo parece bastante elevado en comparación con el mínimo, por lo que convendría revisar ese registro.



Total Claim Amount: las reclamaciones van de aproximadamente 0,38 a 2.893,24.



Customer Lifetime Value: los valores aparecen con el símbolo %. Aunque ya obtuviste sus extremos, el formato es extraño para un indicador económico y debemos verificar qué representa antes de interpretarlo.

#Calcula estadísticas descriptivas, como la media, la mediana, la moda, la desviación estándar y los cuartiles, para comprender la tendencia central y la distribución de los datos de las columnas numéricas. Expón también tus conclusiones a partir de estas estadísticas.

In [35]:
data.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [41]:
#Calculo Media Income, Mediana Income, Moda Income, Desviacion Estandar Income, Q1, Q2 y Q3
print(data['Income'].mean())
print(data['Income'].median())
print(data['Income'].mode())
print(data['Income'].std())
q1 = data['Income'].quantile(0.25)
q2 = data['Income'].quantile(0.50)
q3 = data['Income'].quantile(0.75)
print(q1, q2, q3)

39295.70121381886
36234.0
0    0.0
Name: Income, dtype: float64
30469.427060401842
14072.0 36234.0 64631.0

El ingreso medio (Income) de los clientes es aproximadamente 39.295,70 unidades monetarias.
La mitad de los valores de ingreso está por debajo o en 36.234, y la otra mitad por encima o en ese valor.
El ingreso que aparece con mayor frecuencia es 0.
La desviación estándar es de 30.469,43, lo que refleja una dispersión considerable de los ingresos.
El primer cuartil (Q1) es 14.072 y el tercer cuartil (Q3) es 64.631, por lo que el 50 % central de los ingresos se encuentra aproximadamente entre esos dos valores.
Conclusión general: Los ingresos presentan una dispersión considerable. La media es superior a la mediana, lo que podría indicar que algunos ingresos elevados aumentan el promedio. Además, el valor cero es el que aparece con mayor frecuencia, por lo que convendría revisar esos registros para comprender qué representan.

In [46]:
#Calculo Media Total Claim Amount, Mediana Total Claim Amount, Moda Total Claim Amount, Desviacion Estandar Total Claim Amount, Q1, Q2 y Q3
print(data['Total Claim Amount'].mean())
print(data['Total Claim Amount'].median())
print(data['Total Claim Amount'].mode())
print(data['Total Claim Amount'].std())
q1 = data['Total Claim Amount'].quantile(0.25)
q2 = data['Total Claim Amount'].quantile(0.50)
q3 = data['Total Claim Amount'].quantile(0.75)
print(q1, q2, q3)

404.98690940896364
354.729129
0    321.6
Name: Total Claim Amount, dtype: float64
293.02725992640416
202.157702 354.729129 532.8

- La reclamación media es de aproximadamente 405 unidades monetarias por registro.
- La mediana es inferior a la media. Esto sugiere que algunas reclamaciones de importe elevado podrían estar aumentando el promedio.
- La desviación estándar es de 293,03, lo que refleja diferencias importantes entre los importes de las reclamaciones.
- El 50 % central de los importes está entre 202,16 y 532,80.
Conclusión basada en datos: La compañía podría estudiar las reclamaciones de importe elevado para entender qué tipos de siniestros generan mayores costes. Esto ayudaría a analizar la distribución de los gastos, aunque todavía no podemos afirmar qué clientes o pólizas son más costosos.

In [47]:
#Calculo Media Monthly Premium Auto, Mediana Monthly Premium Auto, Moda Monthly Premium Auto, Desviacion Estandar Monthly Premium Auto, Q1, Q2 y Q3
print(data['Monthly Premium Auto'].mean())
print(data['Monthly Premium Auto'].median())
print(data['Monthly Premium Auto'].mode())
print(data['Monthly Premium Auto'].std())
q1 = data['Monthly Premium Auto'].quantile(0.25)
q2 = data['Monthly Premium Auto'].quantile(0.50)
q3 = data['Monthly Premium Auto'].quantile(0.75)
print(q1, q2, q3)

193.234360410831
83.0
0    65.0
Name: Monthly Premium Auto, dtype: float64
1601.1903685776203
68.0 83.0 109.5

- Muchas primas mensuales se concentran en valores relativamente bajos, como sugiere el intervalo entre los cuartiles.
- Algunos registros tienen primas mucho más altas y podrían estar elevando la media.
- La desviación estándar de 1.601,19 es extraordinariamente alta en comparación con la mediana de 83.
Conclusión bsada en datos: conviene comprobar si hay primas excepcionalmente elevadas, errores de registro o alguna característica del dataset que explique esa diferencia.

In [52]:
print(data['Vehicle Class'].describe())
print(data['Policy Type'].describe())
print(data['GENDER'].describe())
print(data['ST'].describe())
print(data['Education'].describe())

count              1071
unique                6
top       Four-Door Car
freq                576
Name: Vehicle Class, dtype: object
count              1071
unique                3
top       Personal Auto
freq                780
Name: Policy Type, dtype: object
count     954
unique      5
top         F
freq      457
Name: GENDER, dtype: object
count       1071
unique         8
top       Oregon
freq         320
Name: ST, dtype: object
count         1071
unique           6
top       Bachelor
freq           324
Name: Education, dtype: object

1. Vehicle Class: existen 6 categorías diferentes. La más frecuente es Four-Door Car, con 576 registros. Esto indica que los coches de cuatro puertas son la clase de vehículo más representada en los datos analizados.
2. Policy Type: existen 3 categorías diferentes. Personal Auto es la más frecuente, con 780 registros, lo que representa aproximadamente el 72,8 % de los valores no ausentes. Por tanto, predominan las pólizas de tipo personal.
3. GENDER: hay 5 categorías diferentes y F es la más frecuente, con 457 registros. Además, solo hay 954 valores no ausentes, por lo que esta columna contiene datos faltantes. También conviene revisar las categorías para detectar posibles etiquetas inconsistentes.
4. ST: existen 8 categorías diferentes. Oregon es la más frecuente, con 320 registros. Es recomendable comprobar si algunos estados aparecen escritos con abreviaturas o nombres alternativos, ya que esto podría fragmentar las categorías.
5. Education: existen 6 categorías diferentes. Bachelor es la más frecuente, con 324 registros. Conviene verificar si Bachelor y Bachelors representan la misma categoría, para evitar duplicidades en el análisis.

## Reto 2: Analizar los datos

### Ejercicio 1

El equipo de marketing quiere conocer las 5 ubicaciones de clientes menos frecuentes. Crea una Serie de pandas que contenga las ubicaciones de los clientes y sus frecuencias; después, obtén las 5 ubicaciones menos frecuentes, ordenadas de menor a mayor frecuencia.

In [53]:
# Your code here
data.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [61]:
frequency = data['ST'].value_counts()
print(frequency)

ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [62]:
frequency.sort_values()

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Arizona       186
California    211
Oregon        320
Name: count, dtype: int64

In [63]:
frequency.sort_values().head()

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Ejercicio 2

El equipo de ventas quiere conocer el número total de pólizas vendidas para cada tipo de póliza. Crea una Serie de pandas que contenga los tipos de póliza y el número total de pólizas vendidas para cada uno; después, identifica el tipo de póliza con el mayor número de ventas.

*Pista:*
- *El método `value_counts()` simplifica este análisis.*
- *Además, existe un método que devuelve el índice del valor máximo de una columna o fila.*

In [71]:
# Your code here
ptype = data['Policy Type'].value_counts()
print(ptype)

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [72]:
ptype.idxmax()

'Personal Auto'

### Ejercicio 3

El equipo de ventas quiere saber si los clientes con pólizas *Personal Auto* tienen ingresos inferiores a los clientes con pólizas *Corporate Auto*. ¿Cómo se comparan los ingresos medios de ambos tipos de póliza?

- Utiliza `loc` para crear dos DataFrames: uno que contenga únicamente las pólizas *Personal Auto* y otro que contenga únicamente las pólizas *Corporate Auto*.
- Calcula los ingresos medios de cada tipo de póliza.
- Imprime los resultados.

In [89]:
data.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [90]:
# Your code here
personal_auto = data.loc[data['Policy Type'] == 'Personal Auto']
print(personal_auto)

     Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master
1     QZ44356     Arizona      F              Bachelor
2     AI49188      Nevada      F              Bachelor
4     GA49547  Washington      M  High School or Below
5     OC83172      Oregon      F              Bachelor
...       ...         ...    ...                   ...
1065  XD85577        Cali      M              Bachelor
1066  TM65736      Oregon      M                Master
1067  VJ51327        Cali      F  High School or Below
1068  GS98873     Arizona      F              Bachelor
1070  MY31220  California      F               College

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0
1                 697953.59%      0.0                  94.0
2                1288743.17%  48767.0                 108.0
4                 536307.65%  36357.0                  68.0
5                 825629.78%  62902.0                  69.0
...                      ...      ...                   ...
1065              284226.69%  69417.0                  73.0
1066              305955.03%  38644.0                  78.0
1067             2031499.76%  63209.0                 102.0
1068              323912.47%  16061.0                  88.0
1070              899704.02%  54230.0                 112.0

     Number of Open Complaints    Policy Type  Vehicle Class  \
0                       1/0/00  Personal Auto  Four-Door Car
1                       1/0/00  Personal Auto  Four-Door Car
2                       1/0/00  Personal Auto   Two-Door Car
4                       1/0/00  Personal Auto  Four-Door Car
5                       1/0/00  Personal Auto   Two-Door Car
...                        ...            ...            ...
1065                    1/1/00  Personal Auto  Four-Door Car
1066                    1/1/00  Personal Auto  Four-Door Car
1067                    1/2/00  Personal Auto            SUV
1068                    1/0/00  Personal Auto  Four-Door Car
1070                    1/0/00  Personal Auto   Two-Door Car

      Total Claim Amount
0               2.704934
1            1131.464935
2             566.472247
4              17.269323
5             159.383042
...                  ...
1065           30.874869
1066          361.455219
1067          207.320041
1068          633.600000
1070          537.600000

[780 rows x 11 columns]

In [91]:
corporate_auto = data.loc[data['Policy Type'] == 'Corporate Auto']
print(corporate_auto)

     Customer          ST GENDER             Education  \
3     WW63253  California      M              Bachelor
6     XZ87318      Oregon      F               College
7     CF85061     Arizona      M                Master
8     DY87989      Oregon      M              Bachelor
12    DP39365  California    NaN                Master
...       ...         ...    ...                   ...
1045  WZ31900      Oregon      F              Bachelor
1050  BJ53923     Arizona      M  High School or Below
1052  FB23788      Oregon      M  High School or Below
1056  PI47776      Oregon      F              Bachelor
1059  YG44474      Oregon      M               College

     Customer Lifetime Value   Income  Monthly Premium Auto  \
3                 764586.18%      0.0                 106.0
6                 538089.86%  55350.0                  67.0
7                 721610.03%      0.0                 101.0
8                2412750.40%  14072.0                  71.0
12                879879.70%  77026.0                 110.0
...                      ...      ...                   ...
1045              864970.06%  94389.0                 107.0
1050              260027.21%  51978.0                  66.0
1052              882883.50%  86721.0                 111.0
1056              253070.51%  89451.0                  63.0
1059             1401472.13%  54193.0                 117.0

     Number of Open Complaints     Policy Type  Vehicle Class  \
3                       1/0/00  Corporate Auto            SUV
6                       1/0/00  Corporate Auto  Four-Door Car
7                       1/0/00  Corporate Auto  Four-Door Car
8                       1/0/00  Corporate Auto  Four-Door Car
12                      1/2/00  Corporate Auto  Four-Door Car
...                        ...             ...            ...
1045                    1/0/00  Corporate Auto            SUV
1050                    1/0/00  Corporate Auto  Four-Door Car
1052                    1/0/00  Corporate Auto            SUV
1056                    1/0/00  Corporate Auto  Four-Door Car
1059                    1/0/00  Corporate Auto            SUV

      Total Claim Amount
3             529.881344
6             321.600000
7             363.029680
8             511.200000
12            472.029737
...                  ...
1045           85.063708
1050          144.782152
1052          532.800000
1056           61.769564
1059          720.752945

[234 rows x 11 columns]

In [93]:
print("Personal auto average income is:",personal_auto['Income'].mean())
print("Corporate auto avergae income is: ",corporate_auto['Income'].mean())

Personal auto average income is: 38180.69871794872
Corporate auto avergae income is:  41390.31196581197

### Extra: Ejercicio 4

Tu objetivo es identificar a los clientes con un importe elevado en sus reclamaciones.

**Instrucciones:**

- Vuelve a consultar las estadísticas de `Total Claim Amount` para comprender mejor los datos.
- Para identificar posibles oportunidades de mejora en la retención y la rentabilidad de los clientes, nos centraremos en aquellos que tengan importes elevados en sus reclamaciones. Considera que los importes elevados son los que se encuentran en el 25 % superior de `Total Claim Amount`. Crea un DataFrame de pandas que contenga la información de los clientes cuyo importe de reclamación sea superior al percentil 75.
- Utiliza los métodos de DataFrame para calcular estadísticas descriptivas de los datos correspondientes a los importes elevados de las reclamaciones.

*Nota: al analizar datos, a menudo nos interesa centrarnos en determinados grupos de valores para obtener información útil. Los percentiles nos ayudan a definir estos grupos. Un percentil indica qué porcentaje de los valores de un conjunto de datos queda por debajo de un valor determinado. Por ejemplo, el percentil 75 es el valor por debajo del cual se encuentra el 75 % de los datos. Del mismo modo, el percentil 25 es el valor por debajo del cual se encuentra el 25 % de los datos. Cuando hablamos del 25 % superior, nos referimos a los valores que están por encima del percentil 75, es decir, el cuarto superior de los datos. Por otro lado, el 25 % inferior corresponde a los valores por debajo del percentil 25. Al centrarnos en estos grupos, podemos identificar patrones y tendencias que pueden ayudar a tomar decisiones y actuar.*

*Pista: busca un método que permita obtener el percentil o cuantil 0,75 y 0,25 de una Serie de pandas.*

*Pista 2: consulta la sección «Selección booleana según los valores de una sola columna» en https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
# Your code here